/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.io.BufferedReader;
import java.io.FileReader;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Jaron Chen
 */
public class GUIPlayer extends javax.swing.JFrame {
    //variables that are used in the methods/events
    private List<Player> player = new ArrayList<Player>();
    private CSVRead reader = new CSVRead();
    private int PlayerNumber = 0;
    
    /**
     * Creates new form GUIPlayer
     */
    public GUIPlayer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOutput = new javax.swing.JTable();
        lblOutput = new javax.swing.JLabel();
        btnDisplayPlayer = new javax.swing.JButton();
        spnPlayer = new javax.swing.JSpinner();
        lblPlayer = new javax.swing.JLabel();
        btnPDF = new javax.swing.JButton();
        lblInput = new javax.swing.JLabel();
        btnRead = new javax.swing.JButton();
        txtInput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        tblOutput.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblOutput);

        lblOutput.setText("Achievements");

        btnDisplayPlayer.setText("Display Player");
        btnDisplayPlayer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDisplayPlayerMouseClicked(evt);
            }
        });

        lblPlayer.setText("Player:");

        btnPDF.setText("PDF");
        btnPDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPDFMouseClicked(evt);
            }
        });

        lblInput.setText("File:");

        btnRead.setText("Read File");
        btnRead.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReadMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblOutput)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPlayer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDisplayPlayer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPDF))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblInput)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRead)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExit)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblOutput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(btnDisplayPlayer)
                    .addComponent(spnPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPlayer)
                    .addComponent(btnPDF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInput)
                    .addComponent(btnRead)
                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        //exit button
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnDisplayPlayerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDisplayPlayerMouseClicked
        // this button displays the player at the playernumber index of the arraylist  
        PlayerNumber = (int)spnPlayer.getValue();
        if (PlayerNumber < player.size()) {//this takes the player at the index defined by playernumber
            DefaultTableModel dm = new DefaultTableModel(0, 0);//this is the table model for the ui table
            Player tempPlyr = player.get(PlayerNumber);
            DateFormat df = new SimpleDateFormat("dd/MM/yy HH:mm:ss"); 
            Calendar cal = Calendar.getInstance();//this is for getting the time to output
            String header[] = new String[]{"Description", "Level", "Out of Possible"};//header for the table
            dm.setColumnIdentifiers(header);
            tblOutput.setModel(dm);//setting the table model
            for (int j = 0; j < player.get(PlayerNumber).GetAchievements().size(); j++) {
                dm.addRow(new String[]{player.get(PlayerNumber).GetAchievements().get(j).getDescription(),Integer.toString(player.get(PlayerNumber).GetAchievements().get(j).getLevel()),Integer.toString(player.get(PlayerNumber).GetAchievements().get(j).getMaxLevel())});
                //adding the players achievements to the table model
            }
            lblOutput.setText("Achievements For "+ tempPlyr.getTagName()+ " at "+ df.format(cal.getTime()));
        }
        else
        {//this shows when the playernumber selected is out of nounds of the arraylist
            JOptionPane.showMessageDialog(null, "There are no players at the selected number.", "InfoBox", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnDisplayPlayerMouseClicked

    private void btnPDFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPDFMouseClicked
        //this calls the pdf creator to generate a pdf file of the players and achievements
        PDFGenerator pdf = new PDFGenerator();
        pdf.execute(player);
    }//GEN-LAST:event_btnPDFMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //this code outputs the player, the time, and the players achievements when the program is opened
        reader.Read("C:/Users/Jaron Chen/Documents/JavaAchievement.csv");
        player = reader.ReturnPlayer();//these take the player data from the csv file
        PlayerNumber = (int)spnPlayer.getValue();
        if (PlayerNumber < player.size()) {//this takes the player at the index defined by playernumber
            DefaultTableModel dm = new DefaultTableModel(0, 0);//this is the table model for the ui table
            Player tempPlyr = player.get(PlayerNumber);
            DateFormat df = new SimpleDateFormat("dd/MM/yy HH:mm:ss"); 
            Calendar cal = Calendar.getInstance();//this is for getting the time to output
            String header[] = new String[]{"Description", "Level", "Out of Possible"};//header for the table
            dm.setColumnIdentifiers(header);
            tblOutput.setModel(dm);//setting the table model
            for (int j = 0; j < player.get(PlayerNumber).GetAchievements().size(); j++) {
                dm.addRow(new String[]{player.get(PlayerNumber).GetAchievements().get(j).getDescription(),Integer.toString(player.get(PlayerNumber).GetAchievements().get(j).getLevel()),Integer.toString(player.get(PlayerNumber).GetAchievements().get(j).getMaxLevel())});
                //adding the players achievements to the table model
            }
            lblOutput.setText("Achievements For "+ tempPlyr.getTagName()+ " at "+ df.format(cal.getTime()));
        }
        else
        {//this shows when the playernumber selected is out of nounds of the arraylist
            JOptionPane.showMessageDialog(null, "There are no players at the selected number.", "InfoBox", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnReadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReadMouseClicked
        // button for reading CSV file
        reader.Read(txtInput.getText());
        player = reader.ReturnPlayer();
    }//GEN-LAST:event_btnReadMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPlayer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDisplayPlayer;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPDF;
    private javax.swing.JButton btnRead;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInput;
    private javax.swing.JLabel lblOutput;
    private javax.swing.JLabel lblPlayer;
    private javax.swing.JSpinner spnPlayer;
    private javax.swing.JTable tblOutput;
    private javax.swing.JTextField txtInput;
    // End of variables declaration//GEN-END:variables
}

